FROM pcsml/base

VOLUME /var/opt/pcsml/training-data
VOLUME /var/opt/pcsml/remote-exec-out

# by default, run without $DISPLAY
ENV MPLBACKEND=agg

WORKDIR /opt/pcsml/scratch
COPY src .

#CMD ["bash", "scratch-remote-run.sh"]