FROM ubuntu:17.10

WORKDIR /tmp

# configure apt and install packages
RUN apt-get update \
    && apt-get install -y software-properties-common wget curl nano graphviz unixodbc-dev

####
# expose ssh
# https://docs.docker.com/engine/examples/running_ssh_service/
####
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:[pwd]' | chpasswd
RUN sed -i 's/.*PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/.*Port .*/Port 42202/' /etc/ssh/sshd_config
#RUN echo "Port 42202" >> /etc/ssh/sshd_confg
#RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile


####
# python env setup
####
RUN apt-get update \
    && apt-get -y upgrade python3 \
    && apt-get -y install python3-dev python3-pip

# set python3 as default python
RUN ln -s /usr/bin/python3 /usr/local/bin/python \
    && ln -s /usr/bin/pip3 /usr/local/bin/pip

# python packages
RUN apt-get update \
    && apt-get install -y python3-gdal python3-tk

# gdal, special build to point to headers
RUN pip install \
    azure sqlalchemy pandas geopandas scipy numpy sklearn openpyxl graphviz \
    pyodbc psycopg2 seaborn plotly ipython jupyter

# make sure matplot knows not use X DISPLAY backend

ADD infrastructure/pycharm_helpers.tar.gz /root

VOLUME /var/opt/devel

CMD ["/usr/sbin/sshd", "-D"]